const UPDATE_ITEM_IN_CART_BY_STORE = 'UPDATE_ITEM_IN_CART_BY_STORE';
const REMOVE_ITEM_FROM_CART_BY_STORE = 'REMOVE_ITEM_FROM_CART_BY_STORE';
const CLEAR_CART = 'CLEAR_CART';
const CLEAR_CART_BY_STORE = 'CLEAR_CART_BY_STORE';

export default {
  UPDATE_ITEM_IN_CART_BY_STORE,
  REMOVE_ITEM_FROM_CART_BY_STORE,
  CLEAR_CART,
  CLEAR_CART_BY_STORE,
};
